<?php
/**
 * (c) 2013 CoboltDB
 *
 * @author Werner Roets <cobolt.exe@gmail.com>
 *
 */
 
 require_once('config.php');
 
 if(DEBUG){
	 error_reporting(E_ALL);
	 ini_set('display_errors', 1);
 }


#-----------------------------------------------------------------------------------	
# I N C L U D E S
#---------------------------------------------------------------------------------

	require 'cobolt-db/shared/meekrodb.php';	#meekrodb database lib
	
	# Here we include the core cobolt-db files
	require 'cobolt-db/core/TableObject.php';
	require 'cobolt-db/core/CollectionObject.php';
	require 'cobolt-db/core/TempTable.php';
    
    # Here we include all the custom classes generated by cmd.php
	$classesDir = array (
		'cobolt-db/core/Tables/',
		'cobolt-db/core/Collections/',
	);

	
	foreach ($classesDir as $directory) {
		foreach( glob($directory."*.php") as $filename ){
		
			if (file_exists($filename))
				include $filename;
		}
			
	}
	#-----------------------------------------------------------------------------------	
	# D A T A B A S E
	#-----------------------------------------------------------------------------------	

	#meekro db bindings
	\DB::$user = DB_USER;
	\DB::$password = DB_PASSWORD;
	\DB::$dbName = DB_NAME;
	
	\DB::$error_handler = false; 
	\DB::$throw_exception_on_error = true;